  export const darkTheme = {
    ...{
        fontFamily: "'Helvetica Neue', sans-serif",
        type: "dark",
      },
    colors: {
      accentButtonBg: "#1DC071",
      accentButtonText: "#ffffff",
      primaryButtonBg: "#1DC071",
      primaryButtonText: "#ffffff",
      connectedButtonBg: "#17a65d",
      connectedButtonBgHover: "#158a50",
      borderColor: "#2c2f32",
      modalBg: "#1c1c24",
      modalOverlayBg: "rgba(0, 0, 0, 0.8)",
      secondaryButtonBg: "#2c2f32",
      secondaryButtonHoverBg: "#383b40",
      secondaryButtonText: "#ffffff",
      tooltipBg: "#1c1c24",
      tooltipText: "#ffffff",
      primaryText: "#ffffff",
      secondaryText: "#b0b3b8",
      tertiaryText: "#646D7A",
      inputAutofillBg: "#2c2f32",
      separatorLine: "#383b40",
      secondaryBg: "#0A0A0A",
      tertiaryBg: "#2c2f32",
      scrollbarBg: "#1c1c24",
      selectedTextBg: "#383b40",
      selectedTextColor: "#ffffff",
      skeletonBg: "#383b40",
      success: "#1DC071",
    },
  };
  
  export const lightTheme = {
    ...{
        fontFamily: "'Helvetica Neue', sans-serif",
        type: "light",
      },
    colors: {
      accentButtonBg: "#ffffff",
      accentButtonText: "#1DC071",
      primaryButtonBg: "#ffffff",
      primaryButtonText: "#1DC071",
      connectedButtonBg: "#e2e8f0",
      connectedButtonBgHover: "#cbd5e1",
      borderColor: "#cbd5e1",
      modalBg: "#edf2f7",
      modalOverlayBg: "rgba(255, 255, 255, 0.8)",
      secondaryButtonBg: "#edf2f7",
      secondaryButtonHoverBg: "#e2e8f0",
      secondaryButtonText: "#1a202c",
      tooltipBg: "#edf2f7",
      tooltipText: "#1a202c",
      primaryText: "#1a202c",
      secondaryText: "#4a5568",
      tertiaryText: "#646D7A",
      inputAutofillBg: "#f7fafc",
      separatorLine: "#e2e8f0",
      secondaryBg: "#FFFFFF",
      tertiaryBg: "#edf2f7",
      scrollbarBg: "#edf2f7",
      selectedTextBg: "#e2e8f0",
      selectedTextColor: "#1a202c",
      skeletonBg: "#e2e8f0",
      success: "#38a169",
    },
  };
  